name: CI
on:
  push:
    branches: [ main ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --extra ci
      - name: Set up README example tests
        run: |
          seq 10 > 1.txt
          seq 10 -2 0 > 2.txt
      - name: Run tests
        run: uv run pytest -v
      - name: Verify README examples, TOC
        run: |
          uv run mdcmd
          uv run mktoc
          git diff --exit-code
      - name: Build and publish to PyPI
        if: startsWith(github.ref, 'refs/tags/') && matrix.python-version == '3.11'
        run: |
          uv build
          uv publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/') && matrix.python-version == '3.11'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --generate-notes
